# Generated by Django 5.1.7 on 2025-03-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.AddField(
            model_name='score',
            name='username',
            field=models.CharField(default='Guest', max_length=255),
        ),
    ]
